### ISSUE TITLE
Create set of common automation recipes

### ISSUE THREAD

**Issue by christian-bromann** [webdriverio/example-recipes#1]
In order to help folks with common automation challenges it would be nice to have a repository with recipes and showcases that is tested and applicable for users through copy&paste.

As an example page for tests I recommend [guineapig.webdriver.io](http://guinea-pig.webdriver.io/). We can follow the format we find on the [Cypress recipe repo](https://github.com/cypress-io/cypress-example-recipes).

Any suggestions on format, and use cases? I could easily think of:

- download/upload (local vs remote)
- drag&drop
- API mocking
- usage of `react$` and `react$$`
- usage of page objects
- ...?

**Comment by ckenst** [comment]
Additional suggestions:

- Use of multiple configuration files
- Use of multiple browsers 
  - Use of containers / docker for browsers
- Use of custom commands
- Test Runner configurations

**Comment by christian-bromann** [comment]
Additional suggestions:

- run webdriverio in variety of pipelines (e.g. GH Action, GitLab etc.)

**Comment by christian-bromann** [comment]
@ckenst would you be open to work on this? Happy to provide help!

**Comment by ckenst** [comment]
> @ckenst would you be open to help work on this? Happy to provide help!

Yes! I think I want to start with custom commands (it's something I'm working on now at work). 

Separate question, should we open discussions for this repo? Might make asking questions / chatting a bit easier than and not through Issues.

**Comment by christian-bromann** [comment]
> Yes! I think I want to start with custom commands (it's something I'm working on now at work).

Awesome, thanks. I will make you a contributor if you aren't already.

> Separate question, should we open discussions for this repo? Might make asking questions / chatting a bit easier than and not through Issues.

Opened the discussions tab, good idea!

**Comment by christian-bromann** [comment]
Added a couple of command examples that are referenced within the official docs based on this PR: https://github.com/webdriverio/webdriverio/pull/9808

I think we can always add more examples, so contributions are welcome.
