### ISSUE TITLE
How to run the example

### ISSUE THREAD

**Issue by TIGeMi** [webdriverio/example-recipes#186]
I get an issue when trying to run an example
![image](https://github.com/webdriverio/example-recipes/assets/57514820/8fc3d4b1-4ab3-49a2-9ce0-66d98fdaa7b4)
Could anyone help me to solve it?

**Comment by christian-bromann** [comment]
@TIGeMi thanks for raising the issue.

I added `cross-env` which will make setting environment variables in Windows seamless. Please pull the latest from `main` branch and let me know if it works for you! Thanks!

**Comment by TIGeMi** [comment]
@christian-bromann Thanks for your response. It works well now.
